### ISSUE TITLE
Cleaning Lady List Site

### ISSUE THREAD

**Issue by Kerrialn** [rectorphp/cleaningladylist.com#1]
- [x] domain - cleaningladylist.com
- [x] Database structure
- [ ] Refactor progress functionality
- [x] Cleaning Lady list Form 
- [x] Deployment -> Digital Ocean -> Docker - @TomasVotruba 
- [x] Deployment automation - @TomasVotruba

**Comment by peter279k** [comment]
Any works I can help on this TODO :)?

**Comment by TomasVotruba** [comment]
Hi, thanks for the offer!

Our main goal is to publish website online now, like we have for https://github.com/rectorphp/getrector.org

Currently I'm strugling with Docker deploy. If you check the failing CI on master, the first 2 workflows are failing for some reason. Could you help to make it green?

**Comment by peter279k** [comment]
> 
> 
> Hi, thanks for the offer!
> 
> Our main goal is to publish website online now, like we have for https://github.com/rectorphp/getrector.org
> 
> Currently I'm strugling with Docker deploy. If you check the failing CI on master, the first 2 workflows are failing for some reason. Could you help to make it green?

Sure. I will look at that and make PR :).

**Comment by TomasVotruba** [comment]
So little update. Deploy is now finished thanks to 1:1 mentoring with @JanMikes . 
Took us 30 minutes to get it done. There were also wrong secret keys with SSH deploy and Docker build

**Comment by TomasVotruba** [comment]
Closing as MVP is done
Thank you @Kerrialn , @peter279k , @janmikes for cooperation :+1:

**Comment by JanMikes** [comment]
🎉
